"""
Starter module for pi-gateway-watch.
Generated by Career Lab.
"""


def health_check():
    return {
        "project": "pi-gateway-watch",
        "status": "starter_ready",
        "safe_to_publish": True,
    }


if __name__ == "__main__":
    print(health_check())
